safe-wind:
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB #文件最大大小
  data:
    redis:
      database: 5 # Redis 数据库索引（默认为 0）
      host: ${REDIS_HOST} # Redis 服务器地址
      port: ${REDIS_PORT} # Redis 服务器连接端口
      password: ${REDIS_PASSWORD} # Redis 服务器连接密码（默认为空）
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 链接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 10 # 连接池中的最大空闲连接

server:
  port: 9300

mybatis:
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: 120cb90eda07377285a3a36c98b0eb4
  # 令牌有效期（默认30分钟）
  expireTime: 30
